### ISSUE TITLE
master is much slower than 0.7a

### ISSUE THREAD

**Issue by adamw** [scalaz/scalaz-stream#395]
Running a simple stream:
```
Process.constant(1)
    .take(10000000)
    .toSource.runLast.run
```
on 0.7a takes 37s, on master (1e6ca4f04b3b0361312cff53bb43fbf256699bd4) 127s.
In extreme cases this leads to an OOM:

```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scalaz.stream.Process$Cont$$anonfun$extend$2.apply(Process.scala:682)
	at scalaz.stream.Process$Cont$$anonfun$extend$2.apply(Process.scala:682)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at scalaz.stream.Process$Cont.extend(Process.scala:682)
	at scalaz.stream.Process$class.disconnect(Process.scala:248)
	at scalaz.stream.Process$Append.disconnect(Process.scala:618)
	at scalaz.stream.Process$$anonfun$disconnect$2.apply(Process.scala:249)
	at scalaz.stream.Process$$anonfun$disconnect$2.apply(Process.scala:249)
	at scalaz.stream.Process$$anonfun$suspend$1.apply(Process.scala:1455)
	at scalaz.stream.Process$$anonfun$suspend$1.apply(Process.scala:1454)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$class.go$1(Process.scala:84)
	at scalaz.stream.Process$class.step(Process.scala:97)
	at scalaz.stream.Process$Append.step(Process.scala:618)
	at scalaz.stream.Process$$anonfun$suspendStep$1.apply(Process.scala:106)
	at scalaz.stream.Process$$anonfun$suspendStep$1.apply(Process.scala:105)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115)
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115)
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:234)
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:234)
```

**Comment by pchlupacek** [comment]
@adamw thanks for reporting this. This is certainly the major issue, and we have problem with streams allocating the vast amount of memory (thats why you see the program to be slower). I didn`t track it yet where the problem is, but since we have minimal case, I hope we can address this quite quickly.

**Comment by pchlupacek** [comment]
OK I got the place that causes this issue

```scala

  def awaitOr[F[_], A, O](req: F[A])(fb: EarlyCause => Process[F, O], cln: A => Process[F, Nothing] = const(halt) _)(rcv: A => Process[F, O]): Process[F, O] = {
    Await(req,
      { (r: EarlyCause \/ A) => Trampoline.delay(Try(r.fold(ec => fb(ec), a => rcv(a) onComplete cln(a) ))) },
      { a: A => Trampoline.delay(cln(a)) })
  }

```

@djspiewak this is that `onComplete` causing the infinite handlers to be stacked up. 

I'll think how to resolve this.

**Comment by pchlupacek** [comment]
@djspiewak I think we have to specialize await1 // receive1 to not have that cln parameter introduced. Doing that will fix the issue. I think same shall be done for receiveL/R/Both 

```scala

def receive1[I, O](rcv: I => Process1[I, O]): Process1[I, O] =
    Await(Get[I],(i:EarlyCause \/ I) => Trampoline.delay(i.fold(_=>halt,rcv)), (_:Any) => Trampoline.delay(halt))

```

Another (and probably preffered) possibility is to remove the `cln` from `await` constructor and introduce `awaitPreempt` with simillar signature for these case where we need to make resources safe when interrupted.

**Comment by djspiewak** [comment]
@pchlupacek I think it might be more straightforward to remove the `onComplete` from `awaitOr` and move that implementation over into a new `bracket` combinator.  I agree that the infinite tower of finalizers is a pretty serious problem here, but I suspect it might be a problem in more than just our own code.

**Comment by pchlupacek** [comment]
Cool. Bracket makes complete sense to me. Will make pr over weekend.

**Comment by djspiewak** [comment]
@pchlupacek We should consider starting to have a rigorous set of benchmarks that we watch, so as to avoid landing in this situation over and over again.  Performance is definitely an area I'd like to improve the library.

**Comment by pchlupacek** [comment]
@djspiewak after more fiddling about this, it seems that issue is in combination of the `onComplete` and the `runLast`. Surprisingly when you do run.run you won't have these issues in the master either. 

Nevertheless, I made the PR with bracket, hence I think this is as well better than current `await` definition and it resolves the thing. Would be interested if you perhaps will find more why this affects only runLast driver. My guess would be that we keep the interim results somehow in driver closed over the `onCompletes` added and as such we get the memory pressure high. 

Code seems to run OK with master if you do `run.run` instead of `runLast.run`. 
I also have made the simple test that fails on the current master and passes with the bracket branch.

**Comment by djspiewak** [comment]
@pchlupacek Could it be the change that revises `runLog` to use `Vector` rather than `IndexedSeq`?  Honestly, `runLast` is a terrible terrible driver and we need to change it (I'll give it some thought and PR a fix soon).
