### ISSUE TITLE
gather and sequence are not stack-safe

### ISSUE THREAD

**Issue by ceedubs** [scalaz/scalaz-stream#444]
The title and a REPL session pretty much say it all. It's worth noting that `eval`, which is similar, is stack-safe.

```scala
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import scalaz.stream._
import scalaz.concurrent.Task

val x = Process.range(0, 100000).map(Task.delay(_)).sequence(3).run.attemptRun

val y = Process.range(0, 100000).map(Task.delay(_)).gather(3).run.attemptRun

val z = Process.range(0, 100000).map(Task.delay(_)).eval.run.attemptRun

// Exiting paste mode, now interpreting.

import scalaz.stream._
import scalaz.concurrent.Task
x: scalaz.\/[Throwable,Unit] = -\/(java.lang.StackOverflowError)
y: scalaz.\/[Throwable,Unit] = -\/(java.lang.StackOverflowError)
z: scalaz.\/[Throwable,Unit] = \/-(())
```

**Comment by ceedubs** [comment]
@runarorama figured this out for me. To paraphrase him:

The problem is that `Future.reduceUnordered` will call `.run` when it sees a Now, which is what `delay` ultimately constructs. That is not stack safe.

You can get around this by using `Task.fork`, which forces that `.run` to happen on a separate logical thread.

So ultimately, I think this needs to be fixed in Future, not here. Shall I close this out? Since most people probably use `Task` as their `F`, it may be worth a heads up somewhere.

**Comment by runarorama** [comment]
```
	at scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:308)
	at scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:304)
	at scalaz.concurrent.Future.listen(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
	at scalaz.Free.resume(Free.scala:73)
	at scalaz.Free.go2$1(Free.scala:118)
	at scalaz.Free.go(Free.scala:122)
	at scalaz.Free.run(Free.scala:172)
	at scalaz.concurrent.Future.listen(Future.scala:76)
	at scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
	at scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:308)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:308)
```

**Comment by pchlupacek** [comment]
I have feeling this is Task/Future/Nondet problem and shall be addressed in scalaz directly. In upcoming release (0.9) we will have own `Task` and then yes, will be worth to have tests for all these cases so we are sure no SOE's in our code .... Thanks for pointing this out.
