### ISSUE TITLE
Inconsistent asynchronous behavior in Docker image

### ISSUE THREAD

**Issue by xanderdunn** [scalaz/scalaz-stream#450]
I'm new to Scala, scalaz, and scalaz-stream, so be ready to correct everything I'm doing wrong.  I'm not sure this is a scalaz-stream bug, but it's quite fishy.  

I created a [minimal example repository](https://github.com/xanderdunn/scalazStreamTrouble) exhibiting the problem.  The README should have enough info to run it both in the working local condition and inside a Docker image.

I have a sender of messages and a consumer of those messages.  The consumer executes a call `nextDelivery()` that blocks until there is a message to be received.  In my example the messages happen to be sent over RabbitMQ, although I imagine some configuration without RabbitMQ would exhibit the same inconsistency.  Since the send and receive `Process`es are run asynchronously, the consumer blocking doesn't interfere with the sender

I ran it locally on a Mac OSX 10.11 with Java 1.8.0_60 and it ran correctly.  
I ran it locally on a much slower Ubuntu 14.04 machine with Java 1.8.0_45 and it also ran correctly.  On these I see:
```
scalaz-rabbitmq-bug admin$ ./build/install/scalaz-rabbitmq-bug/bin/scalaz-rabbitmq-bug
13:37:41.457 [pool-3-thread-6] INFO  scalazproblem.Main$ - Waiting to receive a message...
13:37:42.410 [pool-3-thread-7] INFO  scalazproblem.Main$ - Sending Message1
13:37:42.415 [pool-3-thread-8] INFO  scalazproblem.Main$ - Received message Message1
13:37:42.426 [pool-3-thread-3] INFO  scalazproblem.Main$ - Waiting to receive a message...
13:37:43.431 [pool-3-thread-1] INFO  scalazproblem.Main$ - Sending Message2
13:37:43.433 [pool-3-thread-8] INFO  scalazproblem.Main$ - Received message Message2
13:37:43.433 [pool-3-thread-6] INFO  scalazproblem.Main$ - Waiting to receive a message...
13:37:44.437 [pool-3-thread-2] INFO  scalazproblem.Main$ - Sending Message3
13:37:44.440 [pool-3-thread-7] INFO  scalazproblem.Main$ - Received message Message3
13:37:44.441 [pool-3-thread-2] INFO  scalazproblem.Main$ - Waiting to receive a message...
13:37:45.442 [pool-3-thread-5] INFO  scalazproblem.Main$ - Sending Message4
13:37:45.444 [pool-3-thread-3] INFO  scalazproblem.Main$ - Received message Message4
13:37:45.450 [pool-3-thread-8] INFO  scalazproblem.Main$ - Cleaning up and ending.
<application terminates>
```

On both of those machines, I ran the same code inside a docker image and both had the same incorrect behavior.  It seems to be confined to the docker image, regardless of the host machine.  The docker image runs Ubuntu 14.04 with Java 1.8.0_45.  I see:
```
admin$ docker run --rm $USER/scalaztest bash /start.sh
Warning: PID file not written; -detached was passed.
20:34:27.989 [pool-3-thread-1] INFO  scalazproblem.Main$ - Waiting to receive a message...
<application hangs endlessly>
```
It seems to block on the consumer and never gets around to executing the sender.  

I've got the same version of both the RabbitMQ client library and server (3.5.6) in all the situations.  

If you've got any ideas to try out, let me know.  I can try things quickly since I've already got it all set up.  

Here's the output of `jstack` on the hung process inside a Docker container: 
```
root@dc7851498a31:/# jstack 145
2015-10-21 16:55:43
Full thread dump OpenJDK 64-Bit Server VM (25.45-b02 mixed mode):

"Attach Listener" #13 daemon prio=9 os_prio=0 tid=0x00007fe968094000 nid=0xdc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"DestroyJavaVM" #12 prio=5 os_prio=0 tid=0x00007fe98c00a000 nid=0x99 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"pool-3-thread-1" #11 daemon prio=5 os_prio=0 tid=0x00007fe98c3a1800 nid=0xa5 waiting on condition [0x00007fe97cffe000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000eb29e5b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.rabbitmq.client.QueueingConsumer.nextDelivery(QueueingConsumer.java:220)
	at scalazproblem.Main$$anonfun$receive$1.apply(Main.scala:61)
	at scalazproblem.Main$$anonfun$receive$1.apply(Main.scala:59)
	at scalaz.concurrent.Task$.Try(Task.scala:387)
	at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:287)
	at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:287)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-1-thread-3" #10 prio=5 os_prio=0 tid=0x00007fe964018000 nid=0xa4 waiting on condition [0x00007fe9901a5000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000eb260500> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-1-thread-2" #9 prio=5 os_prio=0 tid=0x00007fe98c201000 nid=0xa3 waiting on condition [0x00007fe9902a6000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000eb260778> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"AMQP Connection 127.0.0.1:5672" #8 prio=5 os_prio=0 tid=0x00007fe98c1fb800 nid=0xa2 runnable [0x00007fe9903a7000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x00000000eb262a38> (a java.io.BufferedInputStream)
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139)
	- locked <0x00000000eb262a78> (a java.io.DataInputStream)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:536)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00007fe98c0a6000 nid=0xa0 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007fe98c0a2800 nid=0x9f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007fe98c0a0800 nid=0x9e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fe98c09e800 nid=0x9d runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fe98c075000 nid=0x9c in Object.wait() [0x00007fe990d7c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000eb263260> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000000eb263260> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fe98c073000 nid=0x9b in Object.wait() [0x00007fe990e7d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000eb263418> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000000eb263418> (a java.lang.ref.Reference$Lock)

"VM Thread" os_prio=0 tid=0x00007fe98c06e000 nid=0x9a runnable

"VM Periodic Task Thread" os_prio=0 tid=0x00007fe98c0ab000 nid=0xa1 waiting on condition

JNI global references: 39
```
It looks like the only thing that isn't waiting on a condition is the RabbitMQ thread that's attempting to consume a message.

**Comment by xanderdunn** [comment]
I changed the blocking consumer code to use `Task.async` on [this branch](https://github.com/xanderdunn/scalazStreamTrouble/tree/taskAsync) but got the same results.  
Old code:
```scala
  def receive(consumer: QueueingConsumer) : Task[String] = {
    Task {
      logger.info("Waiting to receive a message...")
      val message = consumer.nextDelivery().getBody()
      new String(message, "UTF-8")
    }
```

New code:
```scala
  def receive(consumer: QueueingConsumer) : Task[String] = {
    Task async { callback =>
      logger.info("Waiting to receive a message...")
      val message = consumer.nextDelivery().getBody()
      callback(right(new String(message, "UTF-8")))
    }
```

Same output locally and in the docker image.

**Comment by xanderdunn** [comment]
I made another experiment.  I think this makes it fairly clear that it's executing the two processes in serial rather than in parallel.  On [this branch](https://github.com/xanderdunn/scalazStreamTrouble/tree/nonBlockingConsumer) I made a small change so that the consumer no longer blocks:
```scala
  def receive(consumer: QueueingConsumer) : Task[String] = {
    Task {
      logger.info("Receiving a stub")
      //val message = consumer.nextDelivery().getBody()
      //new String(message, "UTF-8")
      "Stub"
    }
```

So, I'd expect to see the consumer just spit out "Stub" as fast as the CPU can handle while the sender does its usual thing.  Locally, that is indeed what I see:
```
admin$ ./build/install/scalaz-rabbitmq-bug/bin/scalaz-rabbitmq-bug
15:13:35.643 [pool-3-thread-6] INFO  scalazproblem.Main$ - Receiving a stub
15:13:35.644 [pool-3-thread-7] INFO  scalazproblem.Main$ - Sending Message1
15:13:35.649 [pool-3-thread-3] INFO  scalazproblem.Main$ - Received message Stub
15:13:35.659 [pool-3-thread-3] INFO  scalazproblem.Main$ - Receiving a stub
15:13:35.659 [pool-3-thread-3] INFO  scalazproblem.Main$ - Received message Stub
15:13:35.660 [pool-3-thread-5] INFO  scalazproblem.Main$ - Receiving a stub
15:13:35.661 [pool-3-thread-4] INFO  scalazproblem.Main$ - Received message Stub
15:13:35.661 [pool-3-thread-4] INFO  scalazproblem.Main$ - Receiving a stub
15:13:35.662 [pool-3-thread-5] INFO  scalazproblem.Main$ - Received message Stub
15:13:35.662 [pool-3-thread-4] INFO  scalazproblem.Main$ - Receiving a stub
15:13:35.662 [pool-3-thread-6] INFO  scalazproblem.Main$ - Received message Stub
15:13:35.663 [pool-3-thread-6] INFO  scalazproblem.Main$ - Receiving a stub
15:13:35.663 [pool-3-thread-7] INFO  scalazproblem.Main$ - Received message Stub
15:13:35.664 [pool-3-thread-1] INFO  scalazproblem.Main$ - Receiving a stub
15:13:35.664 [pool-3-thread-6] INFO  scalazproblem.Main$ - Received message Stub
<... lots and lots of messages until it terminates>
```

But in the docker container I see:
```
admin$ docker run --rm $USER/scalaztest bash /start.sh
Warning: PID file not written; -detached was passed.
22:08:23.174 [pool-3-thread-1] INFO  scalazproblem.Main$ - Receiving a stub
22:08:24.185 [pool-3-thread-1] INFO  scalazproblem.Main$ - Sending Message1
22:08:24.200 [pool-3-thread-1] INFO  scalazproblem.Main$ - Received message Stub
22:08:25.206 [pool-3-thread-1] INFO  scalazproblem.Main$ - Sending Message2
22:08:25.209 [pool-3-thread-1] INFO  scalazproblem.Main$ - Receiving a stub
22:08:26.211 [pool-3-thread-1] INFO  scalazproblem.Main$ - Sending Message3
22:08:26.212 [pool-3-thread-1] INFO  scalazproblem.Main$ - Received message Stub
22:08:26.217 [pool-3-thread-1] INFO  scalazproblem.Main$ - Receiving a stub
22:08:27.218 [pool-3-thread-1] INFO  scalazproblem.Main$ - Sending Message4
22:08:27.220 [pool-3-thread-1] INFO  scalazproblem.Main$ - Received message Stub
22:08:27.229 [pool-3-thread-1] INFO  scalazproblem.Main$ - Cleaning up and ending.
<application terminates>
```

The sender doesn't execute until the consumer executes, and vice versa.  Hence the behavior we see above.  Am I misunderstanding and misusing my wye.merge and runAsync?

**Comment by xanderdunn** [comment]
I created [another branch](https://github.com/xanderdunn/scalazStreamTrouble/tree/rxScala) where I replaced the scalaz-stream code for the consumer with RxScala code for the consumer: 

```scala
  def receive(consumer: QueueingConsumer) : Observable[Option[String]] = {
    Observable(
      subscriber => {
        new Thread(new Runnable() {
          def run() : Unit = {
            if (subscriber.isUnsubscribed) {
              return
            }
            var count = 0
            while(count < 4) {
              val message = consumer.nextDelivery().getBody()
              val action = new String(message, "UTF-8")
              subscriber.onNext(Some(action))
              count += 1
            }
            //subscriber.onNext(None)
            if (!subscriber.isUnsubscribed) {
              subscriber.onCompleted()
            }
          }
        }).start()
      }
    )
  }
```

This performs correctly and identically on both local machine and Docker container, which seems to point to something in scalaz-stream or at least something scalaz-stream relies on that RxScala doesn't.

**Comment by pchiusano** [comment]
@xanderdunn there is too much going on here for us to be much help. I'd suggest opening a proper issue if/when you get the issue more isolated. Closing for now.

Here are some remarks, thoughts - 

* The core scalaz-stream functions are all using pure Scala code, and I doubt that they are somehow behaving differently. What might make a difference is the level of concurrency in your thread pool you are using in various places. You might want to look into this - by default I think it uses the number of processors you have available, but you can also set it explicitly in calls to `wye` and wherever else you are using concurrency.
* I don't know anything about the Rabbit MQ stuff or if that could behave differently when running in a docker container. The first thing I would do is try to remove that from the equation.

**Comment by xanderdunn** [comment]
@pchiusano 

Many thanks.  Your first remark hit the nail on the head.  The Docker container has a single 

For others who encounter a thread pool issue: 
`wye` takes an implicity `Strategy`, shown in its [declaration](https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/wye.scala#L867). The default `Stragey`s are defined [here](https://github.com/scalaz/scalaz/blob/series/7.2.x/concurrent/src/main/scala/scalaz/concurrent/Strategy.scala)
I created a custom `ExecutorService` and passed it to `Strategy.Executor`, which was passed to the `wye`.  I simply ensured that the number of threads is greater than 1, even if there is only a single processor.
